### ISSUE TITLE
Crash on Linux when interacting with certain elements on a webpage

### ISSUE THREAD

**Issue by Tanza3D** [mnottale/uwu#7]
When using this on Linux, loading a webpage works fine. But when trying to click anywhere on it, Unity will immediately crash. Is there any way to fix this, or am I doing something wrong?

On the google homepage, I tested all the buttons I can find. Clicking on the apps dropdown on the top right worked, along with buttons such as the Sign In button, and various other links. When clicking on some of the links in the footer, although the page will load unity will crash shortly after without any interaction.
![image](https://github.com/mnottale/uwu/assets/33783503/944836bb-511e-4475-b0f5-e27cde903764)
![image](https://github.com/mnottale/uwu/assets/33783503/5bb0bd94-200b-4d14-ae19-94a1cf755376)

https://tanza.me loads and functions fine, but https://tanza.me/gallery immediately crashes unity.
![image](https://github.com/mnottale/uwu/assets/33783503/5b2d23ec-caa2-46d8-aac6-55dc289c49e0)

Seems to be something to do with either some effect or javascript or such on one of these pages I'd guess?

**Comment by Tanza3D** [comment]
![image](https://github.com/mnottale/uwu/assets/33783503/918a358f-ec92-42d8-a6ba-88ab3b66c34b)
Attempting to load this Github issue crashes it before it can even render anything.

**Comment by mnottale** [comment]
Can you check your Unity editor logs for some useful hints? IT's at ~/.config/unity3d/Editor.log I think.

**Comment by Tanza3D** [comment]
This is all there is for each crash it seems:
```
Caught fatal signal - signo:11 code:128 errno:0 addr:(nil)
Obtained 4 stack frames.
#0  0x0055aff67eba3c in burst_signal_handler(int, siginfo_t*, void*)
#1  0x007fa37fe4fab0 in __sigaction
#2  0x007fa37fe4f8be in siglongjmp
#3  0xb448e49b3d7bb15f in (Unknown)
Launching bug reporter
```

**Comment by mnottale** [comment]
Doesn't tell much more than SEGV, argh. I'll try to take a look ASAP, I use this binding for game menus so I never change page in my use case, I guess that's where the problem is.

**Comment by Tanza3D** [comment]
okay, thank you! it doesn't seem to just be switching page, loading some pages directly just crash it (such as https://osekai.net or https://tanza.me/portfolio), so it's probably not to do with that i'd suspect

**Comment by mnottale** [comment]
After a bit of investigation my guess is multiple inclusions of ssl lib (both by Unity and by ultralight library) causing symbols mashup, duplicated globals, and eventually crash when doing ssl.

Crash backtrace:

```
#0  0x0000000003a8854c in COMP_CTX_free ()
#1  0x00000000039f14a5 in ssl_clear_cipher_ctx ()
#2  0x00000000039f2509 in SSL_clear ()
#3  0x00000000039d2a38 in ssl3_connect ()
#4  0x00007fff57a7d5fc in ossl_connect_common () at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#5  0x00007fff57a65420 in Curl_ssl_connect_nonblocking () at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#6  0x00007fff57a69f41 in https_connecting () at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#7  0x00007fff57a69f0f in Curl_http_connect () at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#8  0x00007fff57a56007 in multi_runsingle () at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#9  0x00007fff57a55102 in curl_multi_perform () at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#10 0x00007fff5669156c in WebCore::CurlRequestScheduler::workerThread() () at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#11 0x00007fff56691c3d in WTF::Detail::CallableWrapper<WebCore::CurlRequestScheduler::startThreadIfNeeded()::$_2, void>::call() ()
    at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#12 0x00007fff57dc64ed in WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) ()
    at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#13 0x00007fff57e19fb6 in WTF::wtfThreadEntryPoint(void*) () at /bury/beta/opt/Unity/Editor/sdk-linux/bin/libWebCore.so
#14 0x00007fffee694b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#15 0x00007fffee726a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by Tanza3D** [comment]
ahh, hm, that sounds like it'd make sense

**Comment by Tanza3D** [comment]
since it,s an issue with SSL, that would mean that using local files would work perfectly right? if so then i guess i'm sorted, i never considered it being an issue with loading ssl sites

**Comment by mnottale** [comment]
I'm pretty confident the problem lies in SSL indeed, so local files should work fine.

**Comment by SimonSeider** [comment]
would it help if we pack openssl as ssl back-end in the bridge? shouldn't this fix the issue?
